# frozen_string_literal: false

# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file in README.md and
#     CONTRIBUTING.md located at the root of this package.
#
# ----------------------------------------------------------------------------
require 'google/sql/property/databaseinstance_settings_ip_configuration_authorized_networks'
module GoogleInSpec
  module SQL
    module Property
      class DatabaseInstanceSettingsIpConfiguration
        attr_reader :ipv4_enabled

        attr_reader :authorized_networks

        attr_reader :require_ssl

        attr_reader :ssl_mode

        def initialize(args = nil, parent_identifier = nil)
          return if args.nil?
          @parent_identifier = parent_identifier
          @ipv4_enabled = args['ipv4Enabled']
          @authorized_networks = GoogleInSpec::SQL::Property::DatabaseInstanceSettingsIpConfigurationAuthorizedNetworksArray.parse(args['authorizedNetworks'], to_s)
          @require_ssl = args['requireSsl']
          @ssl_mode = args['sslMode']
        end

        def to_s
          "#{@parent_identifier} DatabaseInstanceSettingsIpConfiguration"
        end
      end
    end
  end
end
